import RegisterScreen from './RegisterScreen';
import LoginScreen from './LoginScreen';
import AddPictureScreen from './AddPictureScreen';
import HomeScreen from './HomeScreen';
import SwipeScreen from './SwipeScreen';
import ChatScreen  from './ChatScreen';
import AccountScreen from './AccountScreen';
import AboutMeScreen from './AboutMeScreen';
import AboutMeScreen2 from './AboutMeScreen2';
import SwipePlusScreen from './SwipePlusScreen';
import WelcomeScreen from './WelcomeScreen';
import WhoScreen from './WhoScreen';
import WhereScreen from './WhereScreen';
import LikesScreen from './LikesScreen';
import IdentityScreen from './IdentityScreen';
import RythmePreferenceScreen from './RythmePreferenceScreen';
import PrincipalCaractereScreen from './PrincipalCaractereScreen';
import SaveScreen from './SaveScreen';
import SearchScreen from './SearchScreen';
import WhenBudgetScreen from './WhenBudgetScreen';
import WhereEditScreen from './WhereEditScreen';
import ColocScreen from './ColocScreen';
import GoodOrNotScreen from './GoodOrNotScreen';
import NosFormulesScreen from './NosFormulesScreen';
import LoadScreen from './LoadScreen';

export { RegisterScreen, LoginScreen, AddPictureScreen, HomeScreen, SwipeScreen, AccountScreen, ChatScreen, AboutMeScreen, AboutMeScreen2, SwipePlusScreen, WelcomeScreen, WhoScreen, WhereScreen, LikesScreen, IdentityScreen, RythmePreferenceScreen, PrincipalCaractereScreen, SaveScreen, SearchScreen, WhenBudgetScreen, WhereEditScreen, ColocScreen, GoodOrNotScreen, NosFormulesScreen, LoadScreen };