import RegisterTemplate from './RegisterTemplate';
import LoginTemplate from './LoginTemplate';
import AddPictureTemplate from './AddPictureTemplate';
import HomeTemplate from './HomeTemplate';
import SwipeTemplate from './SwipeTemplate';
import ChatTemplate from './ChatTemplate';
import AccountScreenTemplate from './AccountScreenTemplate';
import AboutMeTemplate from './AboutMeTemplate';
import AboutMe2Template from './AboutMe2Template';
import WelcomeTemplate from './WelcomeTemplate';
import WhoTemplate from './WhoTemplate';
import WhereTemplate from './WhereTemplate';
import LikesTemplate from './LikesTemplate';
import IdentityTemplate from './IdentityTemplate';
import RythmePreferenceTemplate from './RythmePreferenceTemplate';
import PrincipalCaractereTemplate from './PrincipalCaractereTemplate';
import SaveTemplate from './SaveTemplate';
import SearchTemplate from './SearchTemplate';
import WhenBudgetTemplate from './WhenBudgetTemplate';
import ColocTemplate from './ColocTemplate';
import GoodOrNotTemplate from './GoodOrNotTemplate';
import NosFormulesTemplate from './NosFormulesTemplate';

export { RegisterTemplate, LoginTemplate, AddPictureTemplate, HomeTemplate, SwipeTemplate, ChatTemplate, AccountScreenTemplate, AboutMeTemplate, AboutMe2Template, WelcomeTemplate, WhoTemplate, WhereTemplate, LikesTemplate, IdentityTemplate, RythmePreferenceTemplate, PrincipalCaractereTemplate, SaveTemplate, SearchTemplate, WhenBudgetTemplate, ColocTemplate, GoodOrNotTemplate, NosFormulesTemplate };